# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActiveSupport::CurrentAttributes`.
# Please instead update this file by running `bin/tapioca dsl ActiveSupport::CurrentAttributes`.


class ActiveSupport::CurrentAttributes
  include RailsOnSorbetCurrentAttributeMethods
  extend RailsOnSorbetCurrentAttributeMethods

  module RailsOnSorbetCurrentAttributeMethods; end
end
