# typed: true

# DO NOT EDIT MANUALLY
# This is an autogenerated file for dynamic methods in `ActiveRecord::Base`.
# Please instead update this file by running `bin/tapioca dsl ActiveRecord::Base`.


class ActiveRecord::Base; end
